### ISSUE TITLE
Does not run in Node.js 14 environment on AWS Lambda.

### ISSUE THREAD

**Issue by henrythasler** [henrythasler/cloud-tileserver#28]
see [pool.connect() waits forever](https://github.com/brianc/node-postgres/issues/2338).
It works fine on my local Node.js 14 setup. If anyone has a good idea how to solve this, let me know.

**Comment by lklepner** [comment]
Any luck with this?

**Comment by smiffy6969** [comment]
Hi, So i have chased this issue for a day now solid...

AWS SAM node@14
Postgres (10,12,14)
pg 8.7.1

Not specifically Pool, both Pool and Client expiring.

Now i am using this through an MVC stack built for lambda (cerberus-mvc) and the issue i get with pg timing out on the pg middleware (which loads it from service) is actually due to where we require pg in the system.

If i run node 14 on SAM i can only const pg = require('pg') from the handler file and pass it in to the stack.... if i try to load it in the middleware which is a file further down the trace, it loads fine but i get timeouts. Load it in the controller and its fine.

My initial thought was that is was due to an async/await/promise issue, but its not. It is purely where we load the dependency. Doesn't matter what options you send in to pg when using, doesn't matter what version of db you connect to, works totally fine on node 10 and 12 but pg connections timeout on 14 if the require('pg') is anywhere but the handler or the controller.

Clearly this is going to be a loading issue on the dep, somethings not ready somehow, but its only specific to node 14 on AWS SAM (maybe online in lambda too). I am hoping a pg or node up version will solve this, i will continue to use node 12 until 16 is out now (14 broke a lot i hear).

So this is here to help me when i come looking again or if anyone else has this issue, try moving the dep require to the root file handler if your lambdas are more complicated than a single script.

**Comment by henrythasler** [comment]
The issue is fixed in [release v1.3.0](https://github.com/henrythasler/cloud-tileserver/releases/tag/v1.3.0).
